FROM ruby:2.6.0-alpine

RUN apk add --no-cache build-base nodejs sqlite-dev tzdata \
    && gem install bundler \
    && adduser -D app

WORKDIR app/

COPY . .

RUN bundle install \
    && rails db:migrate \
    && chown -R app:app .

USER app

EXPOSE 3000

CMD ["rails", "s"]
