version: '3.5'
services:
    frontend:
      build: ./ml-kurkkumopo-frontend
      ports:
        - 3000:3000
    backend:
      build: ./ml-kurkkumopo-backend
      ports:
        - 5000:5000
      volumes:
        - model:/src/model
        - imgs:/src/imgs
        - data:/data
    training:
      build: ./ml-kurkkumopo-training
      volumes:
        - model:/src/model

volumes:
  model:
  imgs:
  data:
